import type { TemplateDefinition } from '../types/template';
import { SaaSWelcomeEmail, getSaaSWelcomeJsx } from './SaaSWelcomeEmail';
import { OrderReceiptDoc, getOrderReceiptJsx } from './OrderReceiptDoc';
import { TechPulseNewsletter, getTechNewsletterJsx } from './TechPulseNewsletter';
import { ExecutiveReportDoc, getExecutiveReportJsx } from './ExecutiveReportDoc';
import { EventInviteEmail, getEventInviteJsx } from './EventInviteEmail';

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: 'saas-welcome',
    name: 'SaaS Launch & Onboarding',
    category: 'email',
    description: 'Modern onboarding email with hero section, 3-column feature grid, CTA, and social footer.',
    badge: 'Popular Email',
    recommendedMode: 'email',
    defaultCustomization: {
      primaryColor: '#6366f1',
      backgroundColor: '#f8fafc',
      textColor: '#1e293b',
      accentColor: '#4f46e5',
      fontFamily: 'Inter, sans-serif',
      brandName: 'Antigravity SaaS',
      logoUrl: '',
      recipientName: 'Alex Mercer',
      recipientEmail: 'alex.mercer@example.com',
      companyName: 'Antigravity Cloud Inc',
      showCTA: true,
      showSocials: true,
      showFooter: true,
      darkMode: false,
    },
    component: SaaSWelcomeEmail,
    getRawJsx: getSaaSWelcomeJsx,
  },
  {
    id: 'order-receipt',
    name: 'E-Commerce Invoice & Receipt',
    category: 'document',
    description: 'Print-ready invoice & receipt document with company header, itemized pricing table, and totals.',
    badge: 'PDF / Print',
    recommendedMode: 'document',
    defaultCustomization: {
      primaryColor: '#059669',
      backgroundColor: '#f1f5f9',
      textColor: '#0f172a',
      accentColor: '#10b981',
      fontFamily: 'Helvetica, Arial, sans-serif',
      brandName: 'Acme Commerce',
      logoUrl: '',
      recipientName: 'Sarah Jenkins',
      recipientEmail: 'sarah.jenkins@example.com',
      companyName: 'Apex Technologies LLC',
      invoiceNumber: 'INV-2026-9842',
      invoiceDate: 'July 23, 2026',
      totalAmount: '$298.77',
      showCTA: false,
      showSocials: false,
      showFooter: true,
      darkMode: false,
    },
    component: OrderReceiptDoc,
    getRawJsx: getOrderReceiptJsx,
  },
  {
    id: 'tech-newsletter',
    name: 'Tech Pulse Weekly Newsletter',
    category: 'email',
    description: 'High-engagement developer newsletter with issue header, story hero, and 2-column article grid.',
    badge: 'Weekly Digest',
    recommendedMode: 'email',
    defaultCustomization: {
      primaryColor: '#ec4899',
      backgroundColor: '#f3f4f6',
      textColor: '#111827',
      accentColor: '#db2777',
      fontFamily: 'system-ui, sans-serif',
      brandName: 'Frontend Pulse',
      logoUrl: '',
      recipientName: 'Subscriber',
      recipientEmail: 'dev@company.com',
      companyName: 'Pulse Media',
      issueNumber: '42',
      showCTA: true,
      showSocials: true,
      showFooter: true,
      darkMode: false,
    },
    component: TechPulseNewsletter,
    getRawJsx: getTechNewsletterJsx,
  },
  {
    id: 'executive-report',
    name: 'Executive Performance Report',
    category: 'document',
    description: 'Formal corporate briefing report with 4-KPI metric grid, strategic narrative, and sign-offs.',
    badge: 'Corporate Report',
    recommendedMode: 'document',
    defaultCustomization: {
      primaryColor: '#2563eb',
      backgroundColor: '#f8fafc',
      textColor: '#0f172a',
      accentColor: '#1d4ed8',
      fontFamily: 'Georgia, serif',
      brandName: 'Acme Enterprise',
      logoUrl: '',
      recipientName: 'Board of Directors',
      recipientEmail: 'exec@acme.com',
      companyName: 'Acme Holdings Group',
      showCTA: false,
      showSocials: false,
      showFooter: true,
      darkMode: false,
    },
    component: ExecutiveReportDoc,
    getRawJsx: getExecutiveReportJsx,
  },
  {
    id: 'event-invite',
    name: 'VIP Summit & Ticket Pass',
    category: 'email',
    description: 'Exclusive event invitation email complete with date/venue grid, QR ticket pass, and RSVP button.',
    badge: 'Event & Ticket',
    recommendedMode: 'email',
    defaultCustomization: {
      primaryColor: '#8b5cf6',
      backgroundColor: '#faf5ff',
      textColor: '#1e1b4b',
      accentColor: '#7c3aed',
      fontFamily: 'Outfit, sans-serif',
      brandName: 'Elements Summit',
      logoUrl: '',
      recipientName: 'Jordan Lee',
      recipientEmail: 'jordan@techconf.io',
      companyName: 'Unlayer Community',
      eventName: 'Unlayer Elements Global Summit 2026',
      eventDate: 'Thursday, July 31, 2026',
      showCTA: true,
      showSocials: true,
      showFooter: true,
      darkMode: false,
    },
    component: EventInviteEmail,
    getRawJsx: getEventInviteJsx,
  },
];
